### ISSUE TITLE
样式优化问题

### ISSUE THREAD

**Issue by vaevau** [vaucn/wmlqq#9]
1.我觉得左边朋友名字没有必要加上去，顶部有一栏专门显示你在和谁聊天，头像也可以区分（不可能你的朋友都用vau.jpg这张头像)。
2.接受信息样式错误问题，我暂时改不好。应该不是home.sass这里的样式问题。接受到消息之后，重载一下样式就正常了。

**Comment by vaucn** [comment]
1. 如果是群聊，上面显示的是群的名字。 下面不显示人名就看不出是谁了。用这张图片只是暂时的，还没有做上传图片的功能。

2.接受信息后样式的问题我改吧。

**Comment by vaucn** [comment]
发送消息成功后，自己的界面会通过Ajax append新的消息，看messages/create.js.erb这个。
朋友接受到消息后，看room.coffee这个文件。 改进发送的信息和朋友接受到信息没有bubble样式这个问题。

**Comment by vaucn** [comment]
@vaevau 最下面的聊天框不要改。 用原来的宽度。
